.TH build\-openstack\-debian\-image 1
.SH NAME
build\-openstack\-debian\-image \- build a Debian image to be used with OpenStack
.SH SYNOPSIS
.B build\-openstack\-debian\-image
.B \-\-release|\-r <jessie|wheezy>
[ OPTIONS ]

.SH DESCRIPTION
.LP
The
.I build\-openstack\-debian\-image
shell script will build a Debian image which can be used in an OpenStack IaaS
cloud. The resulting (Qcow2 and raw images) contains initramfs\-growroot so
that the root partition will be resized (during the initramfs phase, before
mouting anything) to match the flavor selected when using "nova boot". Later on
during the boot process, cloud\-init will resize the root partition on the fly
(resize is performed when the partition is already mounted read\-write, since
recent kernel allow that for ext3).

Cloud\-init is setup to use an Ec2 metadata server, which is what OpenStack is
compatible with. A "debian" user will be used to receive the ssh key from the
user data blob. This user is setup without a password (eg: adduser
\-\-disabled\-password).  Once logged as this "debian" user in your new virtual
machine, you can "sudo" to root from that user, without needing a password. The
root password is "password" by default, and ssh into the root user without
using an ssh keypair is disabled by default (PermitRootLogin without-password
is set in /etc/ssh/sshd_config).

.SH "PARAMETERS"

.LP
.B \-\-release|\-r
.I wheezy|jessie
.IP

Sets the
.I release
name to be installed. Currently only 2 values a possible:
.I wheezy
and
.I jessie.

.SH "OPTIONS"

.LP
.B \-\-extra\-packages|\-e 
.I PACKAGE,PACKAGE,...
.IP

Select the
.I PACKAGE
you want to add to the image
.I default is: bash-completion,joe,most,screen,less,vim,bzip2

.LP
.B \-\-debootstrap\-url|\-u
.I <debootstrap\-debian\-mirror>
.IP

Select the
.I URL
of the Debian mirror to use to perform the debootstrap. For example:
.I http://ftp.fr.debian.org/debian

.LP
.B \-\-source\-list\-mirror|\-s
.I <source\-list\-mirror>
.IP

URL to use when building the sources.list inside the chroot. If this
option is ommited, then the global http.debian.net redirector is used.
For example, you can use:
.I http://ftp.fr.debian.org/debian

.LP
.B \-\-minimal
.IP

Without this option, the following packages will also be installed:
bash\-completion (and /etc/bash.bashrc will be setup to use bash\-completion),
joe (the text editor), most, GNU screen, less and vim. If you believe that
more things should be added in the non\-minimal image, suggestions are
welcome.

.LP
.B \-\-extra-packages|\-e
.I <package>[,<package>,...]
.IP

Adds extra packages to the virtual machine image.

.LP
.B \-\-hook\-script
.I hook-script
.IP

If you wish to further customize the generated cloud image, you can use a
hook script. When called, build-openstack-debian-image will fill up some
BODI_* environment variable for the hook script to use as per below:

.B BODI_CHROOT_PATH
path where the image is mounted

.B BODI_RELEASE
name of the Debian release that is being bootstraped

.SH AUTHORS

build\-openstack\-debian\-image has been written by Thomas Goirand
<zigo@debian.org>, with contributions from Mehdi Abaakouk
<sileht@sileht.net>.
