.TH build\-openstack\-debian\-image 1
.SH NAME
build\-openstack\-debian\-image \- build a Debian image to be used with OpenStack
.SH SYNOPSIS
.B build\-openstack\-debian\-image
[ OPTIONS ]
.B [ \-\-minimal ]

.SH DESCRIPTION
.LP
.I build\-openstack\-debian\-image
This shell script will build a Debian image which can be used in an OpenStack
IaaS cloud. The resulting (Qcow2 and raw images) contains initramfs\-growroot
so that the root partition will be resized to match the flavor selected when
using "nova boot". Later on the boot process, cloud\-init will resize the root
partition on the fly (resize is performed when the partition is already mounted
read\-write, since recent kernel allow that).

Cloud\-init is setup to use the Ec2 metadata server. A "debian" user will be
used to receive the ssh key from the user data. This user is setup without
a password (eg: adduser \-\-disabled\-password).  You can "sudo" to root from
that user without a password. The root password is "password" by default, and
ssh into the root user with using ssh keys is disabled by default.

.SH "OPTION"

.LP
.B \-\-minimal
.IP
Without this option, the following packages will also be installed:
bash\-completion (and /etc/bash.bashrc will be setup to use bash\-completion),
joe (the text editor), most, GNU screen, less and vim. If you believe that
more things should be added in the non\-minimal image, suggestions are
welcome.

.SH AUTHORS

build\-openstack\-debian\-image has been written by Thomas Goirand
<zigo@debian.org>.
