#!/bin/sh

set -e
set -x

echo "deb http://buster-stein.debian.net/debian buster-stein-backports main
deb http://buster-stein.debian.net/debian buster-stein-backports-nochange main
" >${BODI_CHROOT_PATH}/etc/apt/sources.list.d/buster-stein.list

wget http://buster-stein.debian.net/debian/dists/pubkey.gpg -O ${BODI_CHROOT_PATH}/pubkey.gpg

chroot ${BODI_CHROOT_PATH} apt-key add /pubkey.gpg
chroot ${BODI_CHROOT_PATH} apt-get update
chroot ${BODI_CHROOT_PATH} apt-get install octavia-agent -y

mkdir -p ${BODI_CHROOT_PATH}/etc/systemd/system/octavia-agent.service.wants
chroot ${BODI_CHROOT_PATH} ln -s /lib/systemd/system/octavia-agent-certs-ramfs.service /etc/systemd/system/octavia-agent.service.wants/octavia-agent-certs-ramfs.service
chroot ${BODI_CHROOT_PATH} ln -s /lib/systemd/system/octavia-agent.service /etc/systemd/system/multi-user.target.wants/octavia-agent.service
