#!/bin/sh

set -e
set -x

build-openstack-debian-image --release buster --hook-script `pwd`/amphora-build-hook \
	-u http://mirror.infomaniak.ch/debian \
	-s http://mirror.infomaniak.ch/debian \
	-e cryptsetup,acl,acpid,apparmor,apt-transport-https,at,bash-completion,cloud-guest-utils,cron,curl,dbus,dkms,dmeventd,ifenslave,ifupdown,iptables,iputils-tracepath,irqbalance,less,lsof,net-tools,netbase,netcat-openbsd,open-vm-tools,pollinate,psmisc,rsyslog,socat,tcpdump,uuid-runtime,vim-tiny,vlan,debconf,dbconfig-common \
	--postinstall-packages keepalived,ipvsadm,iputils-ping,haproxy,dkms,ethtool,gawk \
	--password tupeuxpastest \
	--permit-ssh-as-root \
	--security-mirror http://10.4.22.95:9999/security
